/// Feed state management using Riverpod.
///
/// Provides the user's activity feed as a [FutureProvider].
/// The feed is auto-disposed when not in use to save memory.
///
/// Currently only includes scan_complete items generated by the
/// server. Other feed item types (commits, PRs, issues) require
/// GitHub webhook integration.

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/feed_item.dart';
import 'repo_provider.dart';

/// Provider for the user's activity feed.
///
/// Automatically fetches feed items from the backend when watched.
/// Uses [FutureProvider.autoDispose] to cancel requests when the
/// feed screen is not visible.
final feedProvider = FutureProvider.autoDispose<List<FeedItem>>((ref) async {
  final data = ref.watch(chompDataServiceProvider);
  return data.getFeed();
});
